var articles = [
	{
		id: 'cramer-digital-code',
		title: '”Digital Code and Literary Text”',
		author: 'Florian Cramer',
		publication: '<em>BeeHive</em>, 2001',
		iframe: 'https://archive.the-next.org/beehive/preserved/content_apps43/cramer/oop.html'
	},
	{
		id: 'derivepedia-drift-recombination',
		title: '”Derivative as Generative”',
		subtitle: 'Drift, Recombination, and Digital Poetics in Dérivepedia',
		author: 'Mehulkumar Desai',
		publication: '',
		bodyHtml: `<p>Talan Memmott's <em>Dérivepedia</em> stands out as one of the more incisive works of electronic literature to emerge from the mid-2010s. What makes it so compelling is that it does not simply digitise an encyclopedic form like Wikipedia, it turns it inside out. First published in <em>The New River</em> in 2016, Memmott describes the work as “a 'recyclopedic' generator of contextually resist associations” (Memmott). The phrase is unusual, maybe even a little abrasive, but the choice seems deliberate to capture exactly what he wants to achieve through the work. Instead of providing readers with stable entries on stable topics, unlike Wikipedia, <em>Dérivepedia</em> recombines fragments drawn from 400 Wikipedia articles, folds in more than 1000 variables, and mixes these with nearly 200 public-domain images from Wikimedia Commons (Memmott). The result is not a searchable reference system but an anti-reference machine: a drifting textual field that mimics knowledge while exposing the unstable procedures through which knowledge is assembled, circulated, and believed. Hence, read in the broader field of conceptual writing, Memmott's procedure belongs to a tradition defined less by self-expression than by “selection, arrangement, appropriation, and repetition, …as shaped by appropriation, transcription, translation, redaction, repetition” (Andersson). What matters, therefore, is not the invention of original content but the reorganisation of already circulating materials into new relations.</p>
<p>This logic is reinforced on the “About” page where Memmott describes <em>Dérivepedia</em> as “a combinatory and recyclopedic text generator” whose materials are “recombined on the fly” (Memmott). He further explains that the work began through a psychogeographic traversal of Wikipedia itself: moving from one entry to another by hyperlink, appropriating a sentence fragment, then following the next link and continuing the sentence with another fragment, at times across sequences of nineteen to twenty-one entries (Memmott). What matters here is that the work does not use Wikipedia merely as a convenient database. It treats Wikipedia as an environment of movement, discontinuity, and seduction. Wikipedia, thereby, becomes less a repository of information than a terrain through which one drifts.</p>
<p>In <em>Dérivepedia</em>, Memmott proposes not merely a work but an epistemic condition, one that is shaped by drift, assemblage, citation, and recombination. The title itself is already a thesis. It sutures the dérive, the situationist practice of drifting through spaces, structures, and latent psychographies, to the encyclopedic ambition of the “-pedia,” that dream of total knowledge whose promise is always shadowed by incompletion, contingency, and ideological ordering. What emerges from this collision is not a stable archive but a mobile one: a knowledge-form that wanders. Memmott makes this framework explicit in the “About” section of <em>Dérivepedia</em>, where he places the project in relation to Guy Debord's account of drift (Debord), reproducing the well-known formulation about “distinct psychic atmospheres” and the “path of least resistance” that shapes aimless movement through urban space (Memmott). He then translates that spatial logic into informational terms, arguing that Wikipedia permits users to “wander through its information structure,” often in ways “resistant to the development of a contextual plane of consistency” (Memmott). In other words, <em>Dérivepedia</em> does not simply allude to drift as a metaphor, it operationalises drift as a reading practice within networked information culture. It asks what happens when the logic of navigation overtakes the logic of order. If Wikipedia historically seeks system, mastery, and taxonomic clarity, Memmott's <em>Dérivepedia</em> subjects those aspirations to movement, interruption, and detour. The result is something like an anti-totality, though one still haunted by totality's echo in <em>Dérivepedia</em>.</p>
<p>This is why the work should not be dismissed as parody or digital whimsy. Certainly, it may seem funny. Its fabricated article-titles and syntactic collisions generate a comic effect, as though scholarly discourse had been infected by non sequitur. But the comedy is diagnostic. In that sense, <em>Dérivepedia</em> is not only about information. It is also about the subject produced by informational abundance, which is restless, modular, historically overdetermined and never fully self-identical. It reveals how contemporary reading already proceeds: by interruption, lateral linkage, distracted curiosity, and accidental juxtaposition. Long before one arrives ar (is this “as”?) critique, one has already experienced the shape of networked cognition. We do not simply consult knowledge, we pass through it, are sorted by it, fragmented by it, and reassembled within it. In short, in the age of excessive knowledge production, we are not simply prosumer (Toffler 283) of knowledge but at the same time we end up being the product in the knowledge production. <em>Dérivepedia</em> dramatises that condition by making discontinuity visible as form. The reader encounters what looks like coherence, only to discover that coherence has become procedural rather than semantic. Memmott himself underlines this point when he writes that although the generated text “may have the appearance of coherence.” It is actually closed from hundreds of source entries and variable substitutions; it would therefore be “a mistake” to call any individual output an “entry” at all (Memmott). What appears instead are “ephemeral detourned passages” (Memmott). Its form is recombinant because the contemporary consciousness is also recombinant, and the work does not only illustrate this condition from a safe critical distance, but rather it performs it, and therefore, drift becomes method, recombination becomes critique, and the encyclopedia, once a monument to stable reference, reappears as a theatre of unstable relations.</p>
<p>This sense of procedural instability becomes even sharper when read in light of Brian Kim Stefans' discussion of Memmott's earlier digital practice. In Stefans' account, works such as <em>Lexia to Perplexia</em> do not use recombination to generate smooth multiplicity or readerly freedom in any simple sense. They, rather, frustrate stable navigation through hybrid language, graphic excess, and disrupted textual pathways. In this view, recombinant form becomes an aesthetic of difficulty. It does not guide the reader toward mastery but confronts the reader with the unstable conditions of reading in digital environments (Stefans). Seen from this angle, <em>Derivepedia</em> continues Memmott's broader project: not merely recombining information, but making recombination itself felt as a condition of contemporary cognition.</p>
<p>The work's critical importance comes further into focus when read alongside Lev Manovich's influential argument that the database is a defining cultural form of the computer age (Manovich 85). Manovich writes that many new media objects do not tell stories but instead present “collections of individual items,” and he goes so far as to call databases “a new symbolic form” of computer culture (Manovich 80). <em>Dérivepedia</em> belongs squarely within that lineage, but it sharpens the argument by refusing to let databases remain neutral infrastructure. Memmott stages the database as a generator of rhetorical instability. He shows that once knowledge is stored as modular units and traversed through links, authority no longer derives only from content; it also derives from pathways, interfaces, and procedures of assembly. <em>Dérivepedia</em> thus makes database logic legible not as a hidden technical substrate but as an overt aesthetic event through its recombinant form.</p>
<p>To call <em>Dérivepedia</em> “recombinant” is to say that it is more than it samples, collages, or juxtaposes materials. Recombination here is not simply a method of composition, it is the ontology of the work. Fragments here do not precede the whole in an innocent state. They arrive already mediated, already coded by prior systems of circulations, memory, and use designed by the artist. The work's intelligence lies in the sense that it refuses the fantasy that one could restore origin beneath copy. Instead, <em>Dérivepedia</em> asks what becomes possible when one accepts derivation not as lack, but as condition. Derivation can be often opposed to originality, yet this opposition is what the work and the artist dismantles. Hence, this derivation becomes productive. It generates new adjacency, new legibility, new tensions. The derivative here is not secondary; it is generative. In the wider discourse of conceptual writing, this is precisely the point: derivation is not a fallen state opposed to originality, but a primary compositional condition. As Andrea Andersson argues, writing after conceptual art is marked by reduplication and revision, while Seth Price's model of sampling insist that reproduction can itself become “a new beginning” (Andersson).</p>
<p>It becomes crucial to notice that <em>Dérivepedia</em> is not the single work where Talan has played with the recombination to produce the contemporary conditions. In fact, rather than <em>Dérivepedia</em>, <em>Self Portrait(s) [as Other(s)]</em> became illuminating and even caught the attention of many scholars who highlighted the illuminating aspect of self-portrait. As Stefans highlights, recombinant form in Memmott is therefore never merely decorative, it carries a critical force because it exposes the instability of digital authority itself: the fact that coherence, authorship, and intelligibility are procedurally staged rather than naturally given (Stefans). At first glance, both the works may appear to occupy different aesthetic and conceptual registers, as on one hand, <em>Dérivepedia</em> concerns systems of knowledge, circulation, and movement through time and space in knowledge production beyond logical coherence. In short, the journey towards experiencing the world around oneself. <em>Self Portrait(s) [as Other(s)]</em>. On the other hand, it would seem to turn inward, toward identity, reflection, and self-representation, in short it is a journey within, in search of self-identity. However, this apparent contrast is precisely what the Memmott's broader practice unsettles. For in <em>Self Portrait(s) [as Other(s)]</em>, the self is never presented as singular, original, or interior in the old humanistic sense. The “self” there is also assembled, iterative, and citational. It appears not as essence but as arrangement. This point becomes even more compelling in light of Stefans' observation that <em>Self Portrait(s) [as Other(s)]</em> works through the mash-up of already conventionalised cultural materials. What emerges is not a revelation of interior essence, but as an exposure of how the self appears as something assembled from reusable cultural scripts rather than disclosed from within.</p>
<p>However, one cannot deny the fact that <em>Self Portrait(s) [as Other(s)]</em> has a subjective correlation to <em>Dérivepedia</em>. If <em>Dérivepedia</em> shows knowledge as drifting and recombination, <em>Self Portrait(s) [as Other(s)]</em> shows identity as drift and recombination. Wikipedia wanders; so does the self. The knowledge infrastructure fractures; so does the face. In both works, the unit of meaning is not the isolated image, entry, or likeness, but the interval between elements, the gap in which the comparison, displacement, and mutation occur. In this sense, the work does not simply represent subjectivity, it demonstrates that subjectivity itself is recombinant (Stefans). Memmott's great wager is that subjectivity itself can be understood as an editorial event.</p>
<p>This is a radical proposition, in the sense that the portrait has historically been one of the privilege genres through which identity is stabilised. To make a self-portrait is, conventionally, to claim a relation to one's own image: “this is me.” But in <em>Self Portrait(s) [as Other(s)]</em>, that claim becomes troubled. The self comes into view as a construction made from preexisting visual, cultural, and discursive materials. It is less self-presence than self-compilation dependent upon the long recorded history and distant memory. One is tempted to say that these are portraits after identity, works made in the aftermath of the coherent bourgeois subject. However, that phrase would be too final because what Memmott offers instead is not death of the self, but its multiplication. Finally the self survives, but as a mere montage.</p>
<p>Memmott has crafted both the works in the manner that both <em>Dérivepedia</em> and <em>Self Portrait(s) [as Other(s)]</em> must be studied together to understand how contemporary life is organised by recombination across different scales. The first one operates at the scale of culture and knowledge, the other at the scale of the image-body. But both the works reject the fiction of origin. Both the works proceed through appropriation, recontextualisation, and structural drift at various levels. Both ask what truth might look like once authenticity is no longer secured by just singularity. And most importantly, both the works understand that the most urgent aesthetic question is no longer “is that original?” but rather “what relations does this arrangement disclose?”</p>
<p>This last question is crucial because the politics of recombination are never neutral. To rearrange is to intervene in value, visibility, and hierarchy. <em>Dérivepedia</em> does not merely collect and arrange the information, it redistributes significance. It reveals that any knowledge infrastructure, literal or metaphorical, is also a map of power: a decision about what counts, what is linked, what is omitted, and what becomes searchable and hence visible. By reproducing and drifting through such structures rather than submitting to them, the work opens a critical space from which to perceive their hidden architecture. The derive, in this sense, is not just aesthetic play. It is a method of engagement. It allows one to encounter systems not as natural but as developed under the influence of culture, power, and politics.</p>
<p>Similarly, <em>Self Portrait(s) [as Other(s)]</em> estranges the image of the self from the ideological self-possession. The self is shown to be formatted by external codes, in the work thorough genres, media, memories, repetitions, and borrowed signs, whereas the actual recombinant consciousness of the self through cultural values, societal norms, and the other worldly influences. However, the force lies in the fact that this recombination is not presented as simple defeat. Certainly, there is vulnerability here, but also invention. Recombinant identity is precarious, but it is also open to newness. Hence the portrait becomes the site not just of recognition but of experimentation.</p>
<p>What binds these two works most profoundly, then, is their shared understanding of form as a field of negotiation between agency and system. In both the works, Talan neither celebrates free play naively nor laments the loss of authenticity. Instead, he works within the debris of contemporary mediations. He accepts that we inherit a world of copies, metadata, pathways, mirrors, and templates, and asks what kind of aesthetic intelligence still can be exercised there. The answer his works give is striking: intelligence as recombination, critique as relinking, selfhood as a provisional but meaningful remediation.</p>
<p>This is why <em>Dérivepedia</em> should be recognised as an important work. It gives conceptual form to a contemporary experience of the present: that knowledge is navigated rather than possessed, and that navigation itself transforms the navigator. It also clarifies the stakes of Memmott's broader practice by making visible the structural logic that <em>Self Portrait(s) [as Other(s)]</em> renders intimate and embodied. Taken together both the works amount to a theory of contemporary subjectivity. We are, as the work suggests, neither sovereign nor mere passive products. We are composites moving through composite worlds.</p>
<p>The reference page makes this historical and epistemic breath unmistakable. The source field range across linguistic, biology, philosophy, media, politics, visual art, food, empire, literature, and science, including entries such as “Knowledge,” “Donna Haraway,” “Computer Graphics,” “Recombinant DNA,” “Literature Review,” “Algorithm,” “Cabinet of Curiosities,” and “Poststructuralism” (Memmott). This heterogeneity matters. <em>Dérivepedia</em> is not merely mixing random content for surreal effect, it is assembling a miniature model of disciplinary culture itself. The work compresses the modern archive into a recombinant system where the human sciences, natural sciences, pop culture, and historical debris occupy the same procedural plane. That flattening is not innocent. It reflects the epistemic conditions of the web, where radically different discourses become equally available as linked objects, stripped of institutional framing and ripe for recombination. Wikipedia no longer appears as a repository of purified facts but as a mutable aggregate of textual DNA, endlessly capable of resequencing. In this regard, <em>Dérivepedia</em> offers a subtle critique of originality itself. It does not search for unmediated knowledge beneath citation. It shows that digital knowledge is already derivative, modular, edited and recomposable. The brilliance of the work is that it turns that condition into form rather than lamenting it from a distance.</p>
<p>This is perhaps the deepest achievement of <em>Dérivepedia</em>. It does not mourn the recombinant condition from afar, rather it inhabits it rigorously enough to convert it into thought. In doing so, it joins those rare works that do more than represent the documented historical moments: they produce a form adequate to its contradictions. The result is a body of work in which knowledge drifts, portraits multiply, and the self appears not as a fixed image but as an ever-revisable constellation as Hayles's broader point about electronic literature that it demands media-specific reading strategies because the digital medium is not incidental to meaning (Hayles 2008). <em>Dérivepedia</em> demonstrates that principle with unusual clarity. Its significance does not lie in a stable text that could be easily excerpted into print. Its meaning emerges from recombination, variable replacement, hyperlink logic, generated titles, shifting image-citation relations, and the user's encounter with procedural drift. To discuss <em>Dérivepedia</em> without its computational operations would be to miss the work itself.</p>
<p>This makes the work especially legible through Talan Memmott's own theorization of digital poetics. In “Beyond Taxonomy: Digital Poetics and the Problem of Reading,” Memmott argues against treating digital works as though their operative features were merely “superficial” or “interfacial.” Instead, as the Electronic Literature Directory's summary of the essay puts it, those features are “integral,” and digital works must be understood through their “applied poetics” rather than through paraphrase alone (Heckman). That framework is remarkably apt for <em>Dérivepedia</em>. The work cannot be reduced to what any single output says. Its meaning lies in how it works: in its procedures of recombination, in its architecture of linked fragments, and in the reader's experience of unstable navigation. To read <em>Dérivepedia</em> properly is to read its operations, not just its sentences.</p>
<p>Seen this way, <em>Dérivepedia</em> also belongs within the field of code-centered and system-aware writing that critics have long associated with Memmott. Rita Raley, in her influential essay on codework, names Memmott among the “prominent practitioners” of the form and argues that codework produces a “text-object or a text-event” that foregrounds “programming, mechanism, and materiality” (Raley). Even though <em>Dérivepedia</em> is not reducible to codework in a narrow generic sense, Raley's account remains highly relevant: Memmott's art repeatedly makes the hidden machinery of digital textuality perceptible. In <em>Dérivepedia</em>, one feels the combinatory engine behind the prose. The text is not presented as transparent discourse but as an event generated by procedures. Raley's point that codework “makes exterior the interior workings of the computer” helps explain why <em>Dérivepedia</em> feels so oddly self-exposing: it lets the reader sense the machine logic infiltrating the surface of language.</p>
<p>However, the work also reaches back into older avant-garde practices. Its recombinatory procedures echo Dada montage, cut-up aesthetics, and situationist detournement, all while relocating those traditions into the environment of web culture. Scott Rettberg has argued that contemporary electronic literature should be understood in relation to avant-garde movements such as Dada, especially where disruption, appropriation, and anti-systemic play are concerned (Rettberg). <em>Dérivepedia</em> is compelling precisely because it inhabits both sides of that history. It mirrors a culture in which knowledge infrastructures are massive, links are ubiquitous, and meaning is perpetually susceptible to recombination. It is at once a descendant of twentieth-century anti-art procedure and a specifically twenty-first century reflection on platform knowledge. Its juxtapositions are not handcrafted collage in the older modernist sense; they are generated from platformed archives and hyperlinked behavior. Its anti-systemic force emerges paradoxically through the system. That is one reason the work feels historically exact. It updates techniques of montage and detournement for a world in which textual fragments are already discretized, searchable, and technically mobile. If Dada broke inherited forms by cutting and rearranging them, <em>Dérivepedia</em> performs a post-digital sequel: it lets the database do the drifting.</p>
<p>The deeper force of <em>Dérivepedia</em>, then, lies in its critique of authority. Traditional encyclopaedias promise legibility, hierarchy, and reliable contextualisation. Wikipedia complicated that model by introducing collaborative revision, continual incompletion, and hyperlink wandering. Memmott pushes the transformation further. He extracts the fragments, preserves their traceability through a references page, but serves them from explanatory continuity. In doing so, he exposes the fact that knowledge is always already editorial: selected, framed, linked, and arranged. <em>Dérivepedia</em> does not destroy knowledge, it estranges it. By making knowledge drift, it reveals the hidden labor of contextualisation that usually secures authority. What the work offers is not relativism, but a sharper literacy about how informational meaning is made.</p>
<p>For all its procedural wit, however, the work is not simply celebratory. Memmott's rhetoric of drift carries a critical edge. When he writes that Wikipedia allows a movement resistant to “a contextual plane of consistency,” he is not only describing a browser's freedom, he is also indicating the fragility of content under network conditions (Memmott, “About Dérivepedia”). <em>Dérivepedia</em> makes that fragility palpable. Its generated passages often look authentitative for a moment before dissolving into absurdity. This oscillation matters because it trains the reader in a kind of skepticism. The work estranges the rhetoric of knowledge by showing how easily coherence can be procedurally staged. In an age saturated with algorithmic text and interface-driven authority, that lesson has only become more urgent. <em>Dérivepedia</em> is not merely about wandering through information. It is also about the politics of trust in informational form.</p>
<p>One can therefore say that <em>Dérivepedia</em> achieves prominence not because there is an enormous body of scholarship devoted solely to it (in fact there are hardly scholarship devoted to it), but because it condenses, with unusual precision, many of the central concerns of electronic literature: procedurality, database aesthetics, anti-taxonomic form, interface reading, code-conscious poetics, and the unstable vocabulary, “recyclopedic,” “combinatory,” “psychogeographical,” “ephemeral dethroned passages” while Memmott's theoretical writing and the criticism around codework provide the larger conceptual frame (Memmott, “About Dérivepedia”, Raley; Heckman). Taken together, these materials make clear that <em>Dérivepedia</em> is not a novelty piece. It is a rigorous artwork of epistemic drift. It converts browsing into poetics, recombination into critique, and Wikipedia into a machine for exposing the instability of the very order it once promised to secure.</p>
<h3>References</h3>
<p>Andersson, Andrea. “I, Too, Wondered…An Introduction to Conceptual Writing after Conceptual Art.” <em>Postscript: Writing after Conceptual Art</em>, edited by Andrea Andersson, University of Toronto Press; Museum of Contemporary Art Denver, 2018, pp. 1-22. <a href=”https://pages.sandpoints.org/sandpoints/ubu5050ubus-8daa49c3/library/Andrea%20Andersson/Postscript_%20Writing%20After%20Conceptual%20Art%20%28195%29/Postscript_%20Writing%20After%20Conceptual%20Art%20-%20Andrea%20Andersson.pdf” target=”_blank” rel=”noopener”>PDF link</a>.</p>
<p>Debord, Guy. “Theory of the Derive.” <em>Situationist International Anthology</em>, edited and translated by Ken Knabb, Bureau of Public Secrets, 1981, pp. 62-66. <a href=”https://files.libcom.org/files/Situationist%20International%20Anthology.pdf” target=”_blank” rel=”noopener”>PDF link</a>.</p>
<p>Hayles, N. Katherine. <em>Electronic Literature: New Horizons for the Literary</em>. University of Notre Dame Press, 2008.</p>
<p>Heckman, Davin. “Beyond Taxonomy: Digital Poetics and the Problem of Reading.” <em>Electronic Literature Directory</em>, 21 July 2010, <a href=”https://directory.eliterature.org/e-lit-resource/589” target=”_blank” rel=”noopener”>directory.eliterature.org/e-lit-resource/589</a>. Accessed April 1, 2026.</p>
<p>Manovich, Lev. “Database as Symbolic Form.” <em>Convergence: The International Journal of Research into New Media Technologies</em>, vol. 5, no. 2, 1999, pp. 80-99. <a href=”https://doi.org/10.1177/135485659900500206” target=”_blank” rel=”noopener”>doi.org/10.1177/135485659900500206</a>.</p>
<p>Memmott, Talan. “About Dérivepedia.” <em>The New River</em>, Spring 2016. <a href=”https://archive.the-next.eliterature.org/newriver/preserved/spring-2016/derivepedia/about.html” target=”_blank” rel=”noopener”>archive.the-next.eliterature.org</a>. Accessed March 20, 2026.</p>
<p>Memmott, Talan. “Beyond Taxonomy: Digital Poetics and the Problem of Reading.” <em>New Media Poetics: Contexts, Technotexts, and Theories</em>, edited by Adelaide Morris and Thomas Swiss, MIT Press, 2006, pp. 293-306.</p>
<p>Memmott, Talan. <em>DÉRIVEPEDIA</em>. 2016. The NEXT, Vancouver, WA. <a href=”https://the-next.eliterature.org/works/2209/0/0/” target=”_blank” rel=”noopener”>the-next.eliterature.org/works/2209/0/0/</a>. Accessed March 20, 2026.</p>
<p>Memmott, Talan. <em>Self Portrait(s) [as Other(s)]</em>. 2003. The NEXT, Vancouver, WA. <a href=”https://the-next.eliterature.org/works/441/0/0/” target=”_blank” rel=”noopener”>the-next.eliterature.org/works/441/0/0/</a>. Accessed March 21, 2026.</p>
<p>Raley, Rita. “Interface: [Net.Writing] and the Practice of Codework.” <em>electronic book review</em>, 8 Sept. 2002, <a href=”https://electronicbookreview.com/publications/interferences-net-writing-and-the-practice-of-codework/” target=”_blank” rel=”noopener”>electronicbookreview.com</a>.</p>
<p>Rettberg, Scott. “Dada Redux: Elements of Dadaist Practice in Contemporary Electronic Literature.” <em>The Fibreculture Journal</em>, no. 11, 2008. <a href=”https://eleven.fibreculturejournal.org/fcj-071-dada-redux-elements-of-dadaist-practice-in-contemporary-electronic-literature/” target=”_blank” rel=”noopener”>eleven.fibreculturejournal.org</a>.</p>
<p>Stefans, Brian Kim. “Comedies of Separation: Toward a Theory of the Ludic Book.” <em>Journal of Electronic Publishing</em>, vol. 14, no. 2, 2011, University of Michigan Library. <a href=”https://doi.org/10.3998/3336451.0014.207” target=”_blank” rel=”noopener”>doi.org/10.3998/3336451.0014.207</a>.</p>
<p>Toffler, Alvin. <em>The Third Wave</em>. William Morrow, 1980, pp. 282-305. <a href=”https://ia801200.us.archive.org/9/items/TheThirdWave-Toffler/The-Third-Wave_-_Toffler.pdf” target=”_blank” rel=”noopener”>PDF link</a>.</p>`
	},
	{
		id: 'article-3',
		title: '“Article Title Three”',
		author: 'Author Name',
		publication: '<em>Journal Name</em>, Year',
		body: [
			'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.',
			'Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.'
		]
	}
];

var currentIndex = 0;
var _article = document.getElementById('criticism-article');
var _liveRegion = document.getElementById('live-region');
var _navList = document.getElementById('criticism-nav-list');


function renderArticleHTML(article) {
	var byline = article.publication
		? esc(article.author) + ' — ' + article.publication
		: esc(article.author);
	var header = '<h2 id="criticism-heading" class="work-title">' + esc(article.title) + '</h2>' +
		(article.subtitle ? '<p class="work-subtitle">' + esc(article.subtitle) + '</p>' : '') +
		'<p class="curatorial-byline">' + byline + '</p>';
	if (article.iframe) {
		return header + '<iframe src="' + article.iframe + '" class="criticism-embed" title="' + esc(article.title) + '" allowfullscreen></iframe>';
	}
	if (article.bodyHtml) {
		return header + '<div class="curatorial-body">' + article.bodyHtml + '</div>';
	}
	return header +
		'<div class="curatorial-body">' +
		(article.body ? article.body.map(function (p) { return '<p>' + p + '</p>'; }).join('') : '') +
		'</div>';
}

function buildNav() {
	_navList.innerHTML = articles.map(function (article, i) {
		var isCurrent = i === currentIndex;
		return '<li' + (isCurrent ? ' class="active"' : '') + '>' +
			'<a href="#" data-index="' + i + '"' +
			(isCurrent ? ' aria-current="true"' : '') +
			'>' + esc(article.title) + (isCurrent ? ' &lt;' : '') + '</a></li>';
	}).join('');
}

_navList.addEventListener('click', function (e) {
	var link = e.target.closest('a[data-index]');
	if (!link) return;
	e.preventDefault();
	navigateTo(parseInt(link.getAttribute('data-index'), 10));
});

function updateNav(index) {
	_navList.querySelectorAll('li').forEach(function (li, i) {
		var isCurrent = i === index;
		var link = li.querySelector('a');
		li.classList.toggle('active', isCurrent);
		if (isCurrent) {
			link.setAttribute('aria-current', 'true');
		} else {
			link.removeAttribute('aria-current');
		}
		link.textContent = articles[i].title + (isCurrent ? ' <' : '');
	});
}

function navigateTo(index) {
	if (index < 0 || index >= articles.length) return;
	currentIndex = index;

	_article.classList.add('is-transitioning');

	setTimeout(function () {
		_article.innerHTML = renderArticleHTML(articles[index]);
		updateNav(index);
		_liveRegion.textContent = articles[index].title + ' selected';
		_article.classList.remove('is-transitioning');

		var heading = document.getElementById('criticism-heading');
		if (heading) {
			heading.setAttribute('tabindex', '-1');
			heading.focus({ preventScroll: true });
		}
	}, 180);
}

buildNav();
navigateTo(0);
